# Variables
title:         "Bulma Calendar"
description:   "Responsive - Interactive Date/Time Picker"
version:       6.1.19
#url:           "https://doc.mh-s.de/bulma-calendar"

# Build
markdown:      kramdown
permalink:     pretty
includes:      ['assets/css', 'assets/js']
exclude:       ['package.json']
sass:
  sass_dir:    _sass
  style:       compressed
